INSERT INTO public.genres (genre_uuid, genre_name)
VALUES 
    (uuid_generate_v4(), 'adult'),
    (uuid_generate_v4(), 'art'),
    (uuid_generate_v4(), 'biography'),
    (uuid_generate_v4(), 'business'),
    (uuid_generate_v4(), 'childrens'),
    (uuid_generate_v4(), 'classics'),
    (uuid_generate_v4(), 'comedy'),
    (uuid_generate_v4(), 'contemporary'),
    (uuid_generate_v4(), 'cookbooks'),
    (uuid_generate_v4(), 'crime'),
    (uuid_generate_v4(), 'fantasy'),
    (uuid_generate_v4(), 'fiction'),
    (uuid_generate_v4(), 'novels'),
    (uuid_generate_v4(), 'history'),
    (uuid_generate_v4(), 'horror'),
    (uuid_generate_v4(), 'humor'),
    (uuid_generate_v4(), 'literature'),
    (uuid_generate_v4(), 'memoir'),
    (uuid_generate_v4(), 'music'),
    (uuid_generate_v4(), 'mistery'),
    (uuid_generate_v4(), 'nonfiction'),
    (uuid_generate_v4(), 'paranormal'),
    (uuid_generate_v4(), 'philosophy'),
    (uuid_generate_v4(), 'poetry'),
    (uuid_generate_v4(), 'psychology'),
    (uuid_generate_v4(), 'religion'),
    (uuid_generate_v4(), 'romance'),
    (uuid_generate_v4(), 'science'),
    (uuid_generate_v4(), 'science fiction'),
    (uuid_generate_v4(), 'self help'),
    (uuid_generate_v4(), 'suspense'),
    (uuid_generate_v4(), 'spirituality'),
    (uuid_generate_v4(), 'sports'),
    (uuid_generate_v4(), 'thriller'),
    (uuid_generate_v4(), 'travel'),
    (uuid_generate_v4(), 'young adult');