package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"

	"github.com/hulhay/ganesha/graph/generated"
)

// Hello is the resolver for the hello field.
func (r *mutationResolver) Hello(ctx context.Context) (*string, error) {
	msg := "helllo"
	return &msg, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
