package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.27

import (
	"context"

	"github.com/hulhay/ganesha/graph/gqlmodel"
)

// GetGenres is the resolver for the getGenres field.
func (r *queryResolver) GetGenres(ctx context.Context) ([]*gqlmodel.Genre, error) {
	res, err := r.genreService.GetGenres(ctx)
	if err != nil {
		return nil, err
	}
	return res, nil
}
