// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type GeneralResponse struct {
	Message   string `json:"message"`
	IsSuccess bool   `json:"isSuccess"`
}

type Genre struct {
	GenreUUID string `json:"genreUuid"`
	GenreName string `json:"genreName"`
}
